version: '3.9'

services:
  db:
    image: postgres:15.1-bullseye
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library

  backend:
    build:
      context: "."
      dockerfile: Dockerfile.backend
    command: ./entrypoint.sh
    environment:
      - DEBUG=False
      - PORT=8000
    depends_on:
      - db
  
  frontend:
    build:
      context: "."
      dockerfile: Dockerfile.frontend
      args:
        REACT_APP_HOST_IP_ADDRESS: /api
    ports:
      - 81:80
