version: '3.9'

services:
  db:
    image: postgres:15.1-bullseye
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "6432:5432"

  # backend:
  #   build:
  #     context: "."
  #     dockerfile: Dockerfile.backend
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - db
  
  frontend:
    build:
      context: "."
      dockerfile: Dockerfile.frontend
    ports:
      - 3000:3000
