# Dockerfile

FROM python:3.9

WORKDIR /code

# Add entrypoint script
COPY entrypoint.sh .
RUN chmod +x entrypoint.sh

# Install requirments
COPY backend/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Mounts the application code to the image
COPY backend .
RUN mkdir media

EXPOSE 8000